"""v3

Revision ID: 270df83af1b9
Revises: 58a84c691653
Create Date: 2015-10-18 10:55:36.338155

"""

# revision identifiers, used by Alembic.
revision = '270df83af1b9'
down_revision = '58a84c691653'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
