"""update1

Revision ID: 4c395d6b404b
Revises: e994a357ef2
Create Date: 2015-11-06 01:20:03.621881

"""

# revision identifiers, used by Alembic.
revision = '4c395d6b404b'
down_revision = 'e994a357ef2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
