"""v2

Revision ID: 58a84c691653
Revises: 4ca1ef608336
Create Date: 2015-10-18 10:45:35.260485

"""

# revision identifiers, used by Alembic.
revision = '58a84c691653'
down_revision = '4ca1ef608336'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
